config/routes.rb
Webstdyroom::Application.routes.draw do

  resources :home
  resources :docomo_api do
    collection do
      post :search
    end
  end

  

end

app/models/docomo_api.rb
require 'open-uri'
class DocomoApi

  APIKEY="634f2f413047424b32674e4161554472626e53766e5442475641552e306b717a4e745745677a4f41774341"

  def self.find_by_query(query)
    request_uri = "https://api.apigw.smt.docomo.ne.jp/knowledgeQA/v1/ask?APIKEY=#{APIKEY}&q=#{CGI.escape(query)}"
    JSON.parse open(request_uri).read
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docomo_api_controller.rb
class DocomoApiController < ApplicationController

  def search
    @response = DocomoApi.find_by_query(params[:query])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docomo_api_helper.rb
module DocomoApiHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/docomo_api/_show.html.slim
= response["message"]["textForDisplay"]

app/views/docomo_api/search.js.erb
$(".docomo-search-result").html("<%= j render("show", response: @response) %>")

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim
= form_tag search_docomo_api_index_path, remote: true do
  = text_field_tag :query, params[:query], placeholder: "わからない事ある？"
  = submit_tag "について訪ねる"
.docomo-search-result

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webstdyroom</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>